### ISSUE TITLE
Create beta version of audio streaming

### ISSUE THREAD

**Issue by HannaLindgren** [stts-se/tillstudpub#13]
- [x] #2 Move from ScriptProcessor to AudioWorklet
- [x] #6 Retrieve browser's audio settings
- [x] #7 Refactoring
- [x] #9 Change name of gocli
- [x] #8 Make file should compile gocli
- [x] #23 Spikes in audio
- [x] Makefiles
- [x] #16 Documentation
- [x] Create build, test and publish release
- [x] Delete older releases
